-- MySQL Script generated by MySQL Workbench
-- Sat Dec 20 01:05:07 2014
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema wanwan
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `wanwan` ;
CREATE SCHEMA IF NOT EXISTS `wanwan` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `wanwan` ;

-- -----------------------------------------------------
-- Table `wanwan`.`cities`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wanwan`.`cities` ;

CREATE TABLE IF NOT EXISTS `wanwan`.`cities` (
  `id` INT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NULL DEFAULT '' COMMENT '城市名称',
  `parent_id` INT NULL COMMENT '城市编码',
  `initial` VARCHAR(3) NULL DEFAULT '' COMMENT '城市拼音首字母',
  `initials` VARCHAR(30) NULL DEFAULT '' COMMENT '城市首字母（每个字首字母）',
  `pinyin` VARCHAR(90) NULL DEFAULT '' COMMENT '城市拼音',
  `suffix` VARCHAR(16) NULL DEFAULT '' COMMENT '城市后缀',
  `code` VARCHAR(20) NULL DEFAULT '',
  `area_code` VARCHAR(10) NULL DEFAULT '' COMMENT '区号',
  `order_factor` INT NULL DEFAULT 0 COMMENT '排序因数',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wanwan`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wanwan`.`users` ;

CREATE TABLE IF NOT EXISTS `wanwan`.`users` (
  `id` INT(11) NULL AUTO_INCREMENT COMMENT 'id',
  `user_name` VARCHAR(50) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NULL DEFAULT '' COMMENT '昵称',
  `password` VARCHAR(200) NULL DEFAULT '' COMMENT '密码',
  `salt` VARCHAR(200) NULL DEFAULT '' COMMENT '密码盐',
  `sex` INT(11) NULL DEFAULT 2 COMMENT '性别：0,女 ; 1,男 ; 2,保密',
  `avatar` VARCHAR(500) NULL DEFAULT '' COMMENT '头像URL',
  `signature` VARCHAR(500) NULL DEFAULT '' COMMENT '签名',
  `album_count` INT NULL DEFAULT 0 COMMENT '专辑数量:默认0',
  `micropost_count` INT NULL DEFAULT 0 COMMENT '作品数量:默认0',
  `follower_count` INT NULL DEFAULT 0 COMMENT '关注的人数:默认0',
  `followed_count` INT NULL DEFAULT 0 COMMENT '粉丝数量:默认0',
  `city_id` INT NULL COMMENT '所在城市Id',
  `city_name` VARCHAR(50) NULL DEFAULT '' COMMENT '城市名称',
  `status` INT NULL DEFAULT 1 COMMENT '用户状态：0,删除 ; 1,正常 ; 2,拉黑 ; 3,冻结',
  `user_type` INT NULL DEFAULT 0 COMMENT '用户类别',
  `user_mall_url` VARCHAR(500) NULL DEFAULT '' COMMENT '用户商城URL',
  `current_coordinate` VARCHAR(60) NULL DEFAULT '' COMMENT '用户当前坐标',
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更改时间',
  `roles` VARCHAR(200) NULL DEFAULT '' COMMENT '用户角色表',
  `plain_password` VARCHAR(40) NULL DEFAULT '123456',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '用户';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
